---
#controls lxd versions, if changed, check epel version and repo urls
ansible_ssh_user: xvia
ansible_ssh_private_key_file: ~/.ssh/xvia_rsa.pub
xroad_instance: central-server
xroad_central_server: cs.xvia.com.br
xroad_security_server_url: http://ss-monitor.xvia.com.br
xroad_member_class: INT
xroad_member_code: MSERV
xroad_subsystem_code: MONITOR

