---
# This playbook installs an X-Road v6 monitor environment to the defined host inventory from a remote package repository

- hosts: database
  become: yes
  become_user: root
  roles:
    - database
  tags:
    - ss
  vars_files:
    - vars_files/remote_repo.yml
    - vars_files/database.yml
